---
title: "Data cleaning"
output: html_notebook
---

Put data files from csv and clean it and later merge it into a data frame.

```{r setup}
library(lubridate)
library(tidyverse)
```

Pull the csv with the measurements
Made a csv using ObjectJ plugin, taking measurements of the specimens from 1995
Odd rows are measurements from the lateral photos and the even rows are measurements from dorsal photos

```{r}
atlantic_croaker_1995_measurements <- read_csv("~/Documents/OneDrive - aguadilla.inter.edu/BS Microbiology Inter/Internship and opportunities/RISE Internship/2022-croakerlarvae-rise/data/atlantic_croaker_1995_measurements.csv")
View(atlantic_croaker_1995_measurements)
```


```{r}
atlantic_croaker_1995_measurements <- atlantic_croaker_1995_measurements %>% 
  mutate(spp_num=rep(1:(nrow(atlantic_croaker_1995_measurements)/2), each=2))
view(atlantic_croaker_1995_measurements)

atlantic_croaker_1995_measurements.r <- atlantic_croaker_1995_measurements %>% 
  group_by(spp_num) %>% 
  summarise(across(2:14, ~ max(.x, na.rm=TRUE)))
```

Pull in data sheet
```{r}
DataSheetPhotos_1995_Micro_undu_only <- read_csv("~/Documents/OneDrive - aguadilla.inter.edu/BS Microbiology Inter/Internship and opportunities/RISE Internship/2022-croakerlarvae-rise/data/DataSheetPhotos_1995_Micro_undu_only.csv")
View(DataSheetPhotos_1995_Micro_undu_only)
```

