---
title: "Summer 2022 lab notebook"
output: html_notebook
---

#May 31
Lunch with mentor (Zoë)
Discussed our project
Introduction to what we are going to be working with
Handed out contract
Email with recap of our discussion and things to download

#June 1
Went to the lab at noon
Signed up and made an account in GitHub
Started using R Studio
Created a notebook and repository
Saved the papers in a Mendeley folder
Began reading papers

#June 2
Read papers in the lab and printed some
Wrote questions to better understand some terminology and asked Zoë 
Started doing a rough draft about what I will say in tomorrow's session at 1:30pm
Wrote a summary of what I've understood so far from the papers 

#June 3
Read papers related to larvae-fish
Talked about our trip to the Marine Reserve, what to bring, at what time we will leave and the week's itinerary (field sampling, fish measurements)
Practiced what I am going to say at the Seminar 1
Started taking the lessons on how to install Swirl and how to use it

#June 6
Went to the field station and took photos of the larvae fish of the Atlantic croaker from 1995
Took 11 pictures of tows 1 and 2 (each) from August 9, 1995, from the side and the top
Took measurements of its height and wrote it on a spreadsheet

#June 7
Continued taking pictures of the vials from August 9, September 14 and September 20, 1995

#June 8
Attended the seminar where we discussed our question set
Did some coding lessons from R Programming 1-5 & 7-9
Finished the vials from September 20 and September 28
Took 110 pictures of the fish
Help with the sorting of the fish from 12:30am-4:00am

#June 9
Returned to the dorms from the Rutgers Marine Field Station 

#June 10
Did the 10th coding lesson from R Programming 
Started doing the chart with the information recovered from the fish from 1995

#June 13
Continued reading papers
Moved papers from Mendeley to Zotero due to problems with plugin
Started reading new papers 
Started mini proposal assignment that's due on Wednesday

#June 14
Finished mini proposal assignment
Read some papers about temperature, morphology and climate change
Downloaded the lessons I was supposed to do in the beginning
Did lessons 1 & 2 from Exploratory data analysis

#June 15
Workshop and seminar in Busch Campus from 12pm until 4pm
Read some papers at the dorm

#June 16
Reviewed my mini proposal and made some corrections to it as recommended
Installed ObjectJ as a pluggin for ImageJ
Downloaded the photos of the fish to ObjectJ, prepared the objects and columns with its respective titles
Did lessons 2-7 from Exploratory data analysis

#June 20
Updated the chart from Google Drive with the data Zoë collected on Friday
Started writing the approach, assignment that's due on Wednesday
Did some coding lessons 8-10

#June 21
Practiced taking the measurements of the fish using ObjectJ
Did lessons 2 and 3 from Getting and Cleaning Data
Did lessons 6, 7 from Statistical Inference
Revised the mini proposal 

#June 22
Workshop from 12:45-2pm
Seminar 2-4pm
Did lessons 9 and 11 from Statistical Inference

#June 23
Did lessons 12-14 from Statistical Inference
Revised the approach with the feedback received yesterday
Started taking measurements of the fish (800-811)

#June 24
Continued taking measurements of the fish (812-835)

#June 27
Continued taking measurements of the fish (836-865)
Edited the mini proposal and started reading about how to write the abstract

#June 28
Edited and finished mini proposal
Wrote the abstract
Continued taking measurements of the fish (866-875)

#June 29
Workshop from 12-2pm
Seminar 2-4pm
Watched videos of cleaning data in R

#June 30
Continued taking measurements of the fish (876-900)
Reviewed abstract's feedback and ways to edit it

#July 1
Finished measuring the fish (901-921)

#July 5
Measured Justin's fish
Edited the abstract
Did the practice_analyses.Rmd
Started the PowerPoint presentation

#July 6
Seminar: How to communicate science effectively and how to structure the 5 min PowerPoint presentation
Field day 

#July 7
Saw an introductory video on Rmarkdown
Edited the PowerPoint presentation
Started pulling data from "ObjectJ", converting it to csv files and then putting it on R
Did data cleaning of the data sheets

#July 8
Brainstorm title for our project
Pull Justin's data into R
Used ggplot to create a linear model

#July 9
Finished creating linear models for Justin's data

#July 11
Continued working on data cleaning for Justin's photos
Started to R lessons

#July 12
Finished data cleaning with Justin's measurements and mine 
Saved in the file
Created new notebook to start the analysis
2nd day of R lessons

#July 13
Seminar, where we practiced our presentation and received feedback
Edited the power point presentation

#July 14
Worked on my analysis and created different plots in order to understand what each one means, to later interpret the data and attach it to the results in PP